# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2abee245b37045c22f4719073011c928"
application_url = "https://lm-argue-flashers-discover.trycloudflare.com"
embedded = true
name = "test01"
handle = "test01-113"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://lm-argue-flashers-discover.trycloudflare.com/auth/callback",
  "https://lm-argue-flashers-discover.trycloudflare.com/auth/shopify/callback",
  "https://lm-argue-flashers-discover.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "affiliatemarketing-test.myshopify.com"
automatically_update_urls_on_dev = true
